name: Reusable macOS workflow

on:
  workflow_call:
    inputs:
      build-type:
        default: RelWithDebInfo
        type: string

jobs:
  macOS:
    name: macos-arm64

    runs-on: macos-latest

    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_EMOJI: true
      HOMEBREW_NO_INSTALL_CLEANUP: true
      CMAKE_BUILD_TYPE: ${{ inputs.build-type }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: CI/before_install.macos.sh

    - name: Prime ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos-arm64-${{ inputs.build-type }}
        max-size: 3G

    - name: Configure
      run: CI/before_script.macos.sh -C

    - name: Build
      run: CI/macos/build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openmw-macos-arm64-${{ github.sha }}
        path: build/*.dmg
